[package]
name = "wikipedia2plain"
version = "0.1.0"
authors = ["Sebastian Humenda <shumenda@gmx.de>"]

[lib]
name = "wikipedia2plain"
path = "src/lib.rs"

[[bin]]
name = "wp2plain"
path = "src/main.rs"

[dependencies]
# for wikipedia
bzip2 = "*"
xml-rs = "0.3"
tempdir = "*"
# for pandoc
pandoc = { git = "file:///home/streicher/daten/quellen/foreign/rust-pandoc" }
json = "*"
# for the main program
getopts = "0.2"
